export const CHILD_NAMES = {
  girls: [
    { name: 'Zeynep', meaning: 'Babasının süsü, değerli taşlar.' },
    { name: 'Elif', meaning: 'Dost, tanıdık. Alfabenin ilk harfi.' },
    { name: 'Meryem', meaning: 'İbadete düşkün, dindar kadın.' },
    { name: 'Defne', meaning: 'Güzel kokulu, yaprakları her mevsim yeşil ağaç.' },
    { name: 'Asya', meaning: 'Şifa veren, tedavi eden.' },
    { name: 'Hira', meaning: 'Arayış, Hz. Muhammed’e ilk vahyin geldiği mağara.' },
    { name: 'Zehra', meaning: 'Çok parlak, beyaz yüzlü.' },
    { name: 'Esma', meaning: 'İsimler, adlar. Çok yüksek.' },
    { name: 'Lina', meaning: 'Cennet bahçesindeki küçük bir hurma ağacı.' },
    { name: 'Azra', meaning: 'Üstünde hiç yürünmemiş kum. El değmemiş.' },
    { name: 'Ebrar', meaning: 'İyi, özü sözü doğru, dindar.' },
    { name: 'Eylül', meaning: 'Yılın dokuzuncu ayı. Sonbahar.' },
    { name: 'Miray', meaning: 'Ay gibi parlayan, yılın ilk aylarında doğan.' },
    { name: 'Nisa', meaning: 'Kadınlar. Kur’an-ı Kerim’in 4. suresi.' },
    { name: 'Alya', meaning: 'Şeref, dağ tepesi, yüksek yer.' },
    { name: 'Duru', meaning: 'Berrak, saf, temiz.' },
    { name: 'Sare', meaning: 'Saf, temiz. Hz. İbrahim’in eşi.' },
    { name: 'Melek', meaning: 'Allah ile kul arasındaki elçi.' },
    { name: 'Sudenaz', meaning: 'Nazlı, cilveli, boyalı.' },
    { name: 'Buğlem', meaning: 'Cenneti müjdeleyen melek.' },
    { name: 'İrem', meaning: 'Cennet bahçesi gibi görkemli yer.' },
    { name: 'Hüma', meaning: 'Saadet, devlet ve talih kuşu.' },
    { name: 'Beren', meaning: 'Güçlü, kuvvetli, akıllı.' },
    { name: 'Ecem', meaning: 'Kraliçem, sevgili kraliçe.' },
    { name: 'Güneş', meaning: 'Gök cismi, ışık kaynağı.' },
    { name: 'İkra', meaning: 'Oku. Kur’an’ın ilk emri.' },
    { name: 'Mina', meaning: 'Liman, gökyüzü. Mekke’de bir yer.' },
    { name: 'Nil', meaning: 'Mısır’daki ünlü nehir. Mavi, lacivert.' },
    { name: 'Pelin', meaning: 'Keskin kokulu bir bitki.' },
    { name: 'Rüya', meaning: 'Düş, uykuda görülen hayal.' },
    { name: 'Selin', meaning: 'Gür akan su, müjde.' },
    { name: 'Talia', meaning: 'Güzel, şirin. Şans, talih.' },
    { name: 'Umay', meaning: 'Talih, şans. Koruyucu tanrıça.' },
    { name: 'Vuslat', meaning: 'Kavuşma, ulaşma.' },
    { name: 'Yaren', meaning: 'Dost, arkadaş.' },
    { name: 'Almila', meaning: 'Kızıl elma.' },
    { name: 'Belinay', meaning: 'Ayın göle yansıması.' },
    { name: 'Ceylin', meaning: 'Cennet kapısı.' },
    { name: 'Damla', meaning: 'Çok küçük miktarda su.' },
    { name: 'Evin', meaning: 'Bir şeyin özü, cevheri.' },
    { name: 'Feyza', meaning: 'Bolluk, çokluk, ilim.' },
    { name: 'Gökçe', meaning: 'Gök rengi, güzel, yiğit.' },
    { name: 'Hazal', meaning: 'Kurumuş yapraklar.' },
    { name: 'Irmak', meaning: 'Akarsuların en büyüğü.' },
    { name: 'Jülide', meaning: 'Karmaşık, dağınık saçlı.' },
    { name: 'Kübra', meaning: 'En büyük, çok büyük olan.' },
    { name: 'Lale', meaning: 'Soğanlı bir süs bitkisi.' },
    { name: 'Melis', meaning: 'Bal arısı, tatlı şey.' },
    { name: 'Neva', meaning: 'Ses, ahenk, güç.' },
    { name: 'Öykü', meaning: 'Hikaye, masal.' },
    { name: 'Pınar', meaning: 'Yerden çıkan su kaynağı.' },
    { name: 'Ravza', meaning: 'Bahçe, cennet bahçesi.' },
    { name: 'Sude', meaning: 'Sürülmüş, ezilmiş, boyanmış.' },
    { name: 'Şevval', meaning: 'Hicri takvimin onuncu ayı.' },
    { name: 'Tuğba', meaning: 'Cennetteki iyilik ağacı.' },
    { name: 'Ülkü', meaning: 'Ulaşılmak istenen yüce amaç.' },
    { name: 'Verda', meaning: 'Gül.' },
    { name: 'Yağmur', meaning: 'Gökten düşen su damlaları.' },
    { name: 'Zülal', meaning: 'Saf, berrak, tatlı soğuk su.' },
    { name: 'Ada', meaning: 'Sularla çevrili kara parçası.' },
    { name: 'Bade', meaning: 'Şarap, aşk, kutsal sevgi.' },
    { name: 'Canan', meaning: 'Sevgili, gönül verilen.' },
    { name: 'Dilara', meaning: 'Gönül süsleyen, sevgili.' },
    { name: 'Eda', meaning: 'Tavır, naz, ödeme.' },
    { name: 'Feride', meaning: 'Eşi benzeri olmayan.' },
    { name: 'Güliz', meaning: 'Gül yetiştiren, gül izi.' },
    { name: 'Hande', meaning: 'Gülüş, gülme.' },
    { name: 'Işıl', meaning: 'Parlaklık, parıltı.' },
    { name: 'İpek', meaning: 'İnce, kibar, değerli kumaş.' },
    { name: 'Kayra', meaning: 'Lütuf, ihsan, iyilik.' },
    { name: 'Leyla', meaning: 'Çok karanlık gece.' },
    { name: 'Müge', meaning: 'İnci çiçeği.' },
    { name: 'Nalan', meaning: 'İnleyen, figan eden.' },
    { name: 'Özlem', meaning: 'Hasret, kavuşma isteği.' },
    { name: 'Parla', meaning: 'Işık saç, parla.' },
    { name: 'Reyhan', meaning: 'Güzel kokulu bitki, fesleğen.' },
    { name: 'Seda', meaning: 'Ses, yankı.' },
    { name: 'Şule', meaning: 'Alev, ateş dili.' },
    { name: 'Tülin', meaning: 'Ayna, ayın çevresindeki hale.' },
    { name: 'Ufuk', meaning: 'Gök ile yerin birleştiği yer.' },
    { name: 'Vildan', meaning: 'Yeni doğmuş çocuklar.' },
    { name: 'Yonca', meaning: 'Çayır bitkisi.' },
    { name: 'Zerrin', meaning: 'Altından yapılmış, parlak.' },
    { name: 'Ahsen', meaning: 'En güzel, çok güzel.' },
    { name: 'Bahar', meaning: 'Mevsim, gençlik dönemi.' },
    { name: 'Ceren', meaning: 'Ceylan, güzel gözlü.' },
    { name: 'Didem', meaning: 'Gözüm, sevdiğim.' },
    { name: 'Esra', meaning: 'Gece yolculuğu.' },
    { name: 'Fulya', meaning: 'Nergis türü bir çiçek.' },
    { name: 'Gizem', meaning: 'Sır, çözülemeyen şey.' },
    { name: 'Hale', meaning: 'Ayın çevresindeki ışık halkası.' },
    { name: 'İdil', meaning: 'Kır şiiri, saf aşk.' },
    { name: 'Jale', meaning: 'Çiy, kırağı.' },
    { name: 'Kardelen', meaning: 'Karda açan çiçek.' },
    { name: 'Leman', meaning: 'Parlamak, parıltı.' },
    { name: 'Mine', meaning: 'İnce ve parlak nakış.' },
    { name: 'Nermin', meaning: 'Yumuşak, nazik.' },
    { name: 'Öznur', meaning: 'Özü ışıklı, aydınlık.' },
    { name: 'Rana', meaning: 'Güzel, göze hoş gelen.' },
    { name: 'Sibel', meaning: 'Buğday başağı, yağmur damlası.' }
  ],
  boys: [
    { name: 'Ömer', meaning: 'Yaşayış, hayat, canlılık.' },
    { name: 'Yusuf', meaning: 'İnleyen, ah eden. Hz. Yusuf.' },
    { name: 'Ali', meaning: 'Yüce, ulu, yüksek.' },
    { name: 'Hamza', meaning: 'Aslan, heybetli, azametli.' },
    { name: 'Kerem', meaning: 'Cömertlik, asalet, bağış.' },
    { name: 'Alparslan', meaning: 'Yiğit, cesur aslan.' },
    { name: 'Eymen', meaning: 'Daha uğurlu, çok şanslı.' },
    { name: 'Miraç', meaning: 'Yükselme, göğe çıkma.' },
    { name: 'Selim', meaning: 'Sağlam, kusursuz, doğru.' },
    { name: 'Yavuz', meaning: 'Mert, cesur, güçlü.' },
    { name: 'Bilal', meaning: 'Su gibi serinleten. İlk müezzin.' },
    { name: 'Eren', meaning: 'Ermiş, yiğit, cesur.' },
    { name: 'Aras', meaning: 'Doğu Anadolu’da bir nehir. Sahip çıkılan.' },
    { name: 'Boran', meaning: 'Şiddetli rüzgar, fırtına.' },
    { name: 'Can', meaning: 'Yaşam, ruh, sevgili.' },
    { name: 'Çınar', meaning: 'Uzun ömürlü bir ağaç türü.' },
    { name: 'Deniz', meaning: 'Büyük su kütlesi.' },
    { name: 'Emir', meaning: 'Buyruk, komutan, prens.' },
    { name: 'Fatih', meaning: 'Fetheden, açan.' },
    { name: 'Görkem', meaning: 'İhtişam, gösteriş.' },
    { name: 'Hakan', meaning: 'Türk hükümdarı, kağan.' },
    { name: 'Ilgaz', meaning: 'Hücum, akın. Çankırı’da dağ.' },
    { name: 'İbrahim', meaning: 'İnananların babası.' },
    { name: 'Kaan', meaning: 'Hanların hanı, hükümdar.' },
    { name: 'Levent', meaning: 'Boylu boslu, yakışıklı.' },
    { name: 'Mert', meaning: 'Sözünün eri, yiğit.' },
    { name: 'Nadir', meaning: 'Az bulunan, değerli.' },
    { name: 'Oğuz', meaning: 'Saf, iyi yaradılışlı. Türk boyu.' },
    { name: 'Poyraz', meaning: 'Kuzeydoğudan esen soğuk rüzgar.' },
    { name: 'Rüzgar', meaning: 'Esinti, zaman, devir.' },
    { name: 'Sarp', meaning: 'Geçilmesi zor, dik.' },
    { name: 'Taha', meaning: 'Kur’an’da bir sure adı.' },
    { name: 'Umut', meaning: 'Beklenti, ümit.' },
    { name: 'Volkan', meaning: 'Yanardağ.' },
    { name: 'Yağız', meaning: 'Esmer, yiğit, doru.' },
    { name: 'Ziya', meaning: 'Işık, aydınlık.' },
    { name: 'Adem', meaning: 'İlk insan. Adam.' },
    { name: 'Barış', meaning: 'Huzur, uzlaşma.' },
    { name: 'Cem', meaning: 'Hükümdar, toplanma.' },
    { name: 'Doruk', meaning: 'Zirve, en yüksek yer.' },
    { name: 'Enes', meaning: 'İnsan, dost. Sahabe adı.' },
    { name: 'Furkan', meaning: 'Doğruyu yanlıştan ayıran.' },
    { name: 'Güney', meaning: 'Bir yön.' },
    { name: 'Halil', meaning: 'Sadık dost.' },
    { name: 'Işık', meaning: 'Aydınlık, nurlar.' },
    { name: 'İsmail', meaning: 'Allah’ı işiten.' },
    { name: 'Kadir', meaning: 'Güçlü, değer, onur.' },
    { name: 'Lütfi', meaning: 'Hoş, nazik, iyilikle ilgili.' },
    { name: 'Murat', meaning: 'İstek, dilek, amaç.' },
    { name: 'Numan', meaning: 'Kan, gelincik.' },
    { name: 'Okan', meaning: 'Anlayan, öğrenen.' },
    { name: 'Özgür', meaning: 'Bağımsız, hür.' },
    { name: 'Polat', meaning: 'Çelik, sert, güçlü.' },
    { name: 'Safa', meaning: 'Gönül şenliği, eğlence.' },
    { name: 'Şahin', meaning: 'Yırtıcı bir kuş.' },
    { name: 'Tarık', meaning: 'Sabah yıldızı, yol.' },
    { name: 'Ulaş', meaning: 'Erişmek, yetişmek.' },
    { name: 'Vural', meaning: 'Vur ve al.' },
    { name: 'Yaman', meaning: 'Güçlü, becerikli.' },
    { name: 'Zafer', meaning: 'Başarı, yenme.' },
    { name: 'Alper', meaning: 'Yiğit kişi.' },
    { name: 'Batuhan', meaning: 'Güçlü hükümdar.' },
    { name: 'Cihan', meaning: 'Dünya, kainat.' },
    { name: 'Doğan', meaning: 'Yırtıcı bir kuş.' },
    { name: 'Ediz', meaning: 'Yüksek, değerli.' },
    { name: 'Fikret', meaning: 'Düşünce, fikir.' },
    { name: 'Gökhan', meaning: 'Göklerin hükümdarı.' },
    { name: 'Hüseyin', meaning: 'Küçük sevgili, güzel.' },
    { name: 'Ilgar', meaning: 'Akın, çabuk.' },
    { name: 'İrfan', meaning: 'Bilme, anlama.' },
    { name: 'Kemal', meaning: 'Olgunluk, bilgi.' },
    { name: 'Mete', meaning: 'Büyük Türk hükümdarı.' },
    { name: 'Nihat', meaning: 'Doğa, huy.' },
    { name: 'Onur', meaning: 'Şeref, haysiyet.' },
    { name: 'Ömer', meaning: 'Canlılık, hayat.' },
    { name: 'Pamir', meaning: 'Orta Asya’da bir yayla.' },
    { name: 'Sadi', meaning: 'Uğurlu, şanslı.' },
    { name: 'Şerif', meaning: 'Kutsal, şerefli.' },
    { name: 'Taylan', meaning: 'İnce, uzun boylu.' },
    { name: 'Utku', meaning: 'Zafer, başarı.' },
    { name: 'Vedat', meaning: 'Sevgi, dostluk.' },
    { name: 'Yasin', meaning: 'Kur’an’da bir sure.' },
    { name: 'Zeki', meaning: 'Akıllı, zihin gücü yüksek.' },
    { name: 'Aykut', meaning: 'Kutlu ay.' },
    { name: 'Berk', meaning: 'Sert, sağlam, şimşek.' },
    { name: 'Coşkun', meaning: 'Heyecanlı, coşkulu.' },
    { name: 'Demir', meaning: 'Sert metal, güçlü.' },
    { name: 'Efe', meaning: 'Yiğit, ağabey.' },
    { name: 'Ferit', meaning: 'Eşsiz, tek.' },
    { name: 'Gazi', meaning: 'Savaştan sağ dönen.' },
    { name: 'Hasan', meaning: 'Güzel, iyi davranan.' },
    { name: 'İlker', meaning: 'Birinci, ilk doğan erkek.' },
    { name: 'Koray', meaning: 'Kor gibi parlayan ay.' },
    { name: 'Metin', meaning: 'Sağlam, dayanıklı.' },
    { name: 'Ozan', meaning: 'Şair, halk ozanı.' },
    { name: 'Semih', meaning: 'Cömert, eli açık.' },
    { name: 'Tuna', meaning: 'Görkemli, bir nehir.' },
    { name: 'Uğur', meaning: 'İyilik, şans.' },
    { name: 'Yiğit', meaning: 'Güçlü, yürekli.' },
    { name: 'Yıldırım', meaning: 'Elektrik boşalması, hızlı.' }
  ]
};
