export const VERSE_POOL = [
  { text: "Sabret! Allah iyilik edenlerin mükafatını zayi etmez.", source: "Hûd, 115" },
  { text: "Şüphesiz güçlükle beraber bir kolaylık vardır.", source: "İnşirâh, 5" },
  { text: "Allah size yardım ederse, sizi yenecek yoktur.", source: "Âl-i İmrân, 160" },
  { text: "Nerede olursanız olun, O sizinle beraberdir.", source: "Hadîd, 4" },
  { text: "Allah sabredenlerle beraberdir.", source: "Bakara, 153" },
  { text: "Kullarım sana Beni sorarlarsa, Ben onlara çok yakınım.", source: "Bakara, 186" },
  { text: "Duanız olmasa Rabbim size ne diye değer versin?", source: "Furkân, 77" },
  { text: "Her nefis ölümü tadacaktır.", source: "Âl-i İmrân, 185" },
  { text: "O, her şeyi hakkıyla bilendir.", source: "Bakara, 29" },
  { text: "İyiliğin karşılığı ancak iyiliktir.", source: "Rahmân, 60" },
  { text: "Rabbim genişlik ver, işimi kolaylaştır.", source: "Tâhâ, 25-26" },
  { text: "Allah, hiç kimseye gücünün üstünde bir şey yüklemez.", source: "Bakara, 286" },
  { text: "Kalpler ancak Allah'ı anmakla huzur bulur.", source: "Ra'd, 28" },
  { text: "O, tövbeleri çokça kabul edendir.", source: "Bakara, 37" },
  { text: "Hüküm ancak Allah'ındır.", source: "Yûsuf, 40" },
  { text: "Gevşemeyin, üzülmeyin; inanıyorsanız üstünsünüz.", source: "Âl-i İmrân, 139" },
  { text: "Şüphesiz Rabbim duayı işitendir.", source: "İbrahim, 39" },
  { text: "Deki: Rabbim ilmimi artır.", source: "Tâhâ, 114" },
  { text: "Allah, güzel davrananları sever.", source: "Bakara, 195" },
  { text: "Biz her şeyi bir ölçüye göre yarattık.", source: "Kamer, 49" },
  { text: "Dosdoğru ol!", source: "Hûd, 112" },
  { text: "Şükrederseniz, size olan nimetimi artırırım.", source: "İbrahim, 7" },
  { text: "Zulmedenler yakında nasıl bir devrimle devrileceklerini görecekler.", source: "Şuarâ, 227" },
  { text: "Allah vaadinden asla dönmez.", source: "Hac, 47" },
  { text: "Her zorlukla beraber bir kolaylık vardır.", source: "İnşirâh, 6" },
  { text: "Yalnız Senden yardım dileriz.", source: "Fâtiha, 5" },
  { text: "Allah size bir hayır dilerse, onu kimse engelleyemez.", source: "Yunus, 107" },
  { text: "O, her an yeni bir iştedir.", source: "Rahmân, 29" },
  { text: "Sizin dininiz size, benim dinim banadır.", source: "Kâfirûn, 6" },
  { text: "Allah nurunu tamamlayacaktır.", source: "Saf, 8" }
];

export const HADITH_POOL = [
  { text: "İnsanların en hayırlısı, insanlara faydalı olandır.", source: "Buhârî" },
  { text: "Ameller niyetlere göredir.", source: "Müslim" },
  { text: "Kolaylaştırınız, zorlaştırmayınız.", source: "Buhârî" },
  { text: "Temizlik imanın yarısıdır.", source: "Müslim" },
  { text: "Müslüman, elinden ve dilinden emin olunan kimsedir.", source: "Buhârî" },
  { text: "Dua, ibadetin özüdür.", source: "Tirmizî" },
  { text: "Gülümsemen bir sadakadır.", source: "Tirmizî" },
  { text: "Hayırlı komşu imandandır.", source: "Buhârî" },
  { text: "İşçinin ücretini alın teri kurumadan veriniz.", source: "İbn Mâce" },
  { text: "Bizi aldatan bizden değildir.", source: "Müslim" },
  { text: "Veren el, alan elden üstündür.", source: "Buhârî" },
  { text: "En hayırlınız, ailesine en iyi davranandır.", source: "Tirmizî" },
  { text: "Sabır, ilk sarsıntı anındadır.", source: "Buhârî" },
  { text: "İlim öğrenmek her Müslüman'a farzdır.", source: "İbn Mâce" },
  { text: "Utanmıyorsan dilediğini yap.", source: "Buhârî" },
  { text: "Güzel söz sadakadır.", source: "Müslim" },
  { text: "Gerçek zenginlik gönül zenginliğidir.", source: "Buhârî" },
  { text: "Hayra vesile olan, o hayrı yapmış gibidir.", source: "Tirmizî" },
  { text: "Birbirinize hediye verin, sevginiz artsın.", source: "Muvatta" },
  { text: "Doğruluktan ayrılmayın.", source: "Müslim" },
  { text: "Sizin en hayırlınız Kur'an'ı öğrenen ve öğretendir.", source: "Buhârî" },
  { text: "Yarım hurma ile de olsa ateşten korunun.", source: "Buhârî" },
  { text: "Allah sizin suretlerinize değil, kalplerinize bakar.", source: "Müslim" },
  { text: "Sizden biriniz, kendisi için istediğini kardeşi için de istemedikçe iman etmiş olmaz.", source: "Buhârî" },
  { text: "Allah, bir iş yaptığınızda onu sağlam yapmanızı sever.", source: "Beyhakî" },
  { text: "Birlikte rahmet, ayrılıkta azap vardır.", source: "Müsned" },
  { text: "Bir kötülük gördüğünüzde onu elinizle, gücünüz yetmezse dilinizle düzeltin.", source: "Müslim" },
  { text: "İki nimet vardır ki, insanların çoğu onlarda aldanmıştır: Sağlık ve boş vakit.", source: "Buhârî" },
  { text: "Utanmak bütünüyle hayırdır.", source: "Müslim" },
  { text: "Az da olsa süreklilik arz eden amel, Allah katında en sevilenidir.", source: "Buhârî" },
  { text: "Sizden biriniz, kendisi için istediğini kardeşi için de istemedikçe iman etmiş olmaz.", source: "Buhârî" },
  { text: "Allah, bir iş yaptığınızda onu sağlam (itkan) yapmanızı sever.", source: "Beyhakî" },
  { text: "Birlikte rahmet, ayrılıkta azap vardır.", source: "Müsned" },
  { text: "Bir kötülük gördüğünüzde onu elinizle, gücünüz yetmezse dilinizle düzeltin.", source: "Müslim" },
  { text: "Zandan sakının, çünkü zan sözlerin en yalanıdır.", source: "Buhârî" },
  { text: "Dünya tatlıdır ve çekicidir.", source: "Müslim" },
  { text: "İki nimet vardır ki, insanların çoğu onlarda aldanmıştır: Sağlık ve boş vakit.", source: "Buhârî" },
  { text: "Mümin, bir delikten iki defa ısırılmaz.", source: "Buhârî" },
  { text: "Utanmak bütünüyle hayırdır.", source: "Müslim" },
  { text: "Az da olsa süreklilik arz eden amel, Allah katında en sevilenidir.", source: "Buhârî" }

];

export const ZIKIR_REHBERI = {
  gunlukDualar: [
    // --- SABAH DUALARI (30 ADET) ---
    { vakit: 'sabah', ad: "Sabahın Nuru", arapca: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ", meal: "Mülk Allah'ın olarak sabaha erdik.", fazilet: "Güne Allah'ın korumasında başlamak içindir." },
    { vakit: 'sabah', ad: "Seyyidül İstiğfar", arapca: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ", meal: "Allah'ım sen benim Rabbimsin.", fazilet: "Cenneti garantileyen istiğfar duasıdır." },
    { vakit: 'sabah', ad: "Rızık Talebi", arapca: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا", meal: "Allah'ım faydalı ilim ve temiz rızık ver.", fazilet: "İşlerin bereketi ve zihin açıklığı içindir." },
    { vakit: 'sabah', ad: "Afiyet Duası", arapca: "اللَّهُمَّ عَافِنِي فِي بَدَنِي", meal: "Allah'ım bedenime sağlık ver.", fazilet: "Gün boyu bedensel ve ruhsal sağlık içindir." },
    { vakit: 'sabah', ad: "Şerlerden Korunma", arapca: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ", meal: "O'nun ismiyle hiçbir şey zarar veremez.", fazilet: "Görünür görünmez kazalardan korur." },
    { vakit: 'sabah', ad: "Hidayet İsteği", arapca: "اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي", meal: "Allah'ım beni doğru yola ilet.", fazilet: "Karar verirken Allah'ın yardımını celp eder." },
    { vakit: 'sabah', ad: "Tembellikten Sığınma", arapca: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكَسَلِ", meal: "Allah'ım tembellikten sana sığınırım.", fazilet: "Günün verimli geçmesi için okunur." },
    { vakit: 'sabah', ad: "Şükür Eda", arapca: "اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ", meal: "Bana ulaşan her nimet sendendir.", fazilet: "Günün şükrünü yerine getirmiş sayılmak içindir." },
    { vakit: 'sabah', ad: "İman Tazeleme", arapca: "رَضِيتُ بِاللَّهِ رَبًّا", meal: "Rab olarak Allah'tan razı oldum.", fazilet: "Allah'ın rızasını kazanmaya vesiledir." },
    { vakit: 'sabah', ad: "Besmele-i Şerif", arapca: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ", meal: "Rahman ve Rahim olan Allah'ın adıyla.", fazilet: "Her hayırlı işin anahtarıdır." },
    { vakit: 'sabah', ad: "Nazar Duası", arapca: "مَا شَاءَ اللَّهُ لَا قُوَّةَ إِلَّا بِاللَّهِ", meal: "Allah ne dilerse o olur.", fazilet: "Göz hapsinden ve nazardan muhafaza eder." },
    { vakit: 'sabah', ad: "Kifayet Duası", arapca: "حَسْبِيَ اللَّهُ وَنِعْمَ الْوَكِيلُ", meal: "Allah bana yeter.", fazilet: "Zorluklara karşı manevi güç verir." },
    { vakit: 'sabah', ad: "Bereket Duası", arapca: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا", meal: "Rızkımızı mübarek kıl.", fazilet: "Elinizdeki imkanların artmasına vesiledir." },
    { vakit: 'sabah', ad: "Selamet Duası", arapca: "يَا سَلَامُ سَلِّمْنَا", meal: "Ey Selam olan, bizi selamette kıl.", fazilet: "Korkulardan emin olmak için okunur." },
    { vakit: 'sabah', ad: "İlahi Yardım", arapca: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ", meal: "Rahmetinle yardım dilerim.", fazilet: "Darda kalanların en büyük sığınağıdır." },
    { vakit: 'sabah', ad: "Felah Duası", arapca: "اللَّهُمَّ اجْعَلْ أَوَّلَ هَذَا النَّهَارِ صَلَاحًا", meal: "Günün başlangıcını hayır kıl.", fazilet: "Güne pozitif ve hayırlı başlamak içindir." },
    { vakit: 'sabah', ad: "Kalp Nurlandırma", arapca: "اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا", meal: "Allah'ım kalbime nur ver.", fazilet: "İç huzuru ve basiret için okunur." },
    { vakit: 'sabah', ad: "Borçtan Kurtulma", arapca: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الدَّيْنِ", meal: "Borç altında kalmaktan sana sığınırım.", fazilet: "Maddi ferahlık ve ödeme kolaylığı içindir." },
    { vakit: 'sabah', ad: "Vesvese Kalkanı", arapca: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ", meal: "Şeytanın şerrinden Allah'a sığınırım.", fazilet: "Negatif düşünceleri uzaklaştırır." },
    { vakit: 'sabah', ad: "Kötü Huydan Sığınma", arapca: "اللَّهُمَّ اهْدِنِي لِأَحْسَنِ الْأَخْلَاقِ", meal: "Beni en güzel ahlaka ilet.", fazilet: "İnsanlarla ilişkilerin düzelmesi içindir." },
    { vakit: 'sabah', ad: "Sıdk Duası", arapca: "اللَّهُمَّ اجْعَلْنِي مِنَ الصَّادِقِينَ", meal: "Beni sadıklardan eyle.", fazilet: "Öz ve söz doğruluğu için okunur." },
    { vakit: 'sabah', ad: "Zikir Güzelliği", arapca: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ", meal: "Seni anmam için bana yardım et.", fazilet: "İbadetlerden tat almak için okunur." },
    { vakit: 'sabah', ad: "Manevi Zırh", arapca: "اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ", meal: "Beni önümden arkamdan koru.", fazilet: "Her yönden gelecek tehlikelere karşı zırhtır." },
    { vakit: 'sabah', ad: "Hikmet Talebi", arapca: "رَبِّ زِدْنِي عِلْمًا", meal: "Rabbim ilmimi artır.", fazilet: "Öğrenme ve anlama kabiliyeti içindir." },
    { vakit: 'sabah', ad: "Dünya Hayrı", arapca: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", meal: "Bize dünyada güzellik ver.", fazilet: "En kapsamlı istek duasıdır." },
    { vakit: 'sabah', ad: "Kabir Emniyeti", arapca: "اللَّهُمَّ قِنِي عَذَابَكَ", meal: "Beni azabından koru.", fazilet: "Ahiret endişesini giderir." },
    { vakit: 'sabah', ad: "Anne Baba Duası", arapca: "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ", meal: "Beni ve ailemi bağışla.", fazilet: "Aile bağlarının manevi gücü içindir." },
    { vakit: 'sabah', ad: "Halis Niyet", arapca: "اللَّهُمَّ اجْعَلْ عَمَلِي خَالِصًا", meal: "Amelimi halis kıl.", fazilet: "İhlas ve samimiyet kazanmak içindir." },
    { vakit: 'sabah', ad: "Güzel Akıbet", arapca: "اللَّهُمَّ أَحْسِنْ عَاقِبَتَنَا", meal: "Akıbetimizi güzel eyle.", fazilet: "İşlerin sonunun hayırlı bitmesi içindir." },
    { vakit: 'sabah', ad: "Teşekkür Duası", arapca: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", meal: "Alemlerin Rabbine hamd olsun.", fazilet: "Nimetin devamlılığını sağlar." },

    // --- AKŞAM DUALARI (30 ADET) ---
    { vakit: 'aksam', ad: "Akşam Huzuru", arapca: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ", meal: "Mülk Allah'ın olarak akşama erdik.", fazilet: "Geceyi huzurla geçirmek içindir." },
    { vakit: 'aksam', ad: "Gece Kalkanı", arapca: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ", meal: "Allah'ın tam kelimelerine sığınırım.", fazilet: "Gece boyu mahlukatın şerrinden korur." },
    { vakit: 'aksam', ad: "Mağfiret Talebi", arapca: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", meal: "Tövbe eder, bağışlanma dilerim.", fazilet: "Günün günahlarını temizlemek içindir." },
    { vakit: 'aksam', ad: "Karanlık Şerrinden", arapca: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", meal: "Felağın Rabbine sığınırım.", fazilet: "Büyü, haset ve karanlık şerleri def eder." },
    { vakit: 'aksam', ad: "Vesvese Savar", arapca: "قُل * أَعُوذُ بِرَبِّ النَّاسِ", meal: "İnsanların Rabbine sığınırım.", fazilet: "İnsi ve cinni şeytanların etkisini kırar." },
    { vakit: 'aksam', ad: "Ayetel Kürsi", arapca: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", meal: "Allah, O'ndan başka ilah yoktur.", fazilet: "Yatağına girerken okuyanı sabaha kadar melek korur." },
    { vakit: 'aksam', ad: "İman Beyanı", arapca: "آمَنَ الرَّسُولُ", meal: "Peygamber iman etti...", fazilet: "Gece okuyana her şey için kafi gelir." },
    { vakit: 'aksam', ad: "Hamd-i Şerif", arapca: "الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَالٍ", meal: "Her hal için Allah'a hamd olsun.", fazilet: "Gece boyu sabır ve tevekkül verir." },
    { vakit: 'aksam', ad: "Nur Duası", arapca: "اللَّهُمَّ اجْعَلْ لِي نُورًا", meal: "Bana bir nur ver.", fazilet: "Kabir ve mahşer aydınlığı içindir." },
    { vakit: 'aksam', ad: "Manevi Teslimiyet", arapca: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ", meal: "Kendimi sana teslim ettim.", fazilet: "Uykuda ruhun emniyeti içindir." },
    { vakit: 'aksam', ad: "Rızık Şükrü", arapca: "اللَّهُمَّ اطْعَمْتَ وَأَسْقَيْتَ", meal: "Yedirdin ve içirdin.", fazilet: "Gıdaların şifaya dönüşmesi içindir." },
    { vakit: 'aksam', ad: "Ölüm Hatırlatması", arapca: "بِاسْمِكَ اللَّهمَّ أَمُوتُ وَأَحْيَا", meal: "Senin isminle ölür ve dirilirim.", fazilet: "Uykuya ibadet sevabı katar." },
    { vakit: 'aksam', ad: "Fakirlikten Sığınma", arapca: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْفَقْرِ", meal: "Fakirlikten sana sığınırım.", fazilet: "Manevi zenginlik ve kanaat içindir." },
    { vakit: 'aksam', ad: "Kabir Aydınlığı", arapca: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ", meal: "Mülk O'nun elindedir.", fazilet: "Mülk Suresi kabir azabına engeldir." },
    { vakit: "aksam", ad: "Tevhid Duası", arapca: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ", meal: "Allah birdir, ortağı yoktur.", fazilet: "Şeytanı sabaha kadar uzak tutar." },
    { vakit: 'aksam', ad: "Huzurlu Uyku", arapca: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ", meal: "Kulların dirileceği gün beni koru.", fazilet: "Kabuslardan emin olmak içindir." },
    { vakit: 'aksam', ad: "Cennet Talebi", arapca: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ", meal: "Allah'ım cenneti isterim.", fazilet: "Günde 3 kez diyen için cennet 'onu al' der." },
    { vakit: 'aksam', ad: "Cehennemden Sığınma", arapca: "اللَّهُمَّ أَجِرْنِي مِنَ النَّارِ", meal: "Beni ateşten koru.", fazilet: "Akşam namazından sonra 7 kez okunması sünnettir." },
    { vakit: 'aksam', ad: "İhlas-ı Kalp", arapca: "قُلْ هُوَ اللَّهُ أَحَدٌ", meal: "De ki; O Allah birdir.", fazilet: "Kur'an'ın üçte birine denktir." },
    { vakit: 'aksam', ad: "Zalim Şerrinden", arapca: "اللَّهُمَّ اكْفِنِيهِمْ بِمَا شِئْتَ", meal: "Onlara karşı bana yet.", fazilet: "Düşman şerrinden emin kılar." },
    { vakit: 'aksam', ad: "Sıkıntı Duası", arapca: "لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ", meal: "Azim ve Halim olan Allah'tan başka ilah yoktur.", fazilet: "Ağır sıkıntıları hafifletir." },
    { vakit: 'aksam', ad: "Güç Duası", arapca: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", meal: "Güç ancak Allah'ındır.", fazilet: "Ruhsal yorgunluğa şifadır." },
    { vakit: 'aksam', ad: "İstikamet Duası", arapca: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي", meal: "Kalbimi dinin üzere sabit kıl.", fazilet: "İman zayıflığına karşı kalkandır." },
    { vakit: 'aksam', ad: "Musibet Duası", arapca: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", meal: "O'ndan geldik, O'na döneceğiz.", fazilet: "Kayıplara karşı sabır verir." },
    { vakit: 'aksam', ad: "Affedici Allah", arapca: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ", meal: "Sen affedicisin, affı seversin.", fazilet: "Hataların silinmesi için en etkili duadır." },
    { vakit: 'aksam', ad: "Göz Nuru", arapca: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا", meal: "Bize göz aydınlığı eş ve nesil ver.", fazilet: "Aile huzuru için okunur." },
    { vakit: 'aksam', ad: "İyilik Duası", arapca: "رَبَّنَا آتِنَا فِي الْآخِرَةِ حَسَنَةً", meal: "Ahirette bize güzellik ver.", fazilet: "Sonsuz saadet talebidir." },
    { vakit: 'aksam', ad: "Meleklerin Duası", arapca: "سُبْحَانَكَ لَا عِلْمَ لَنَا", meal: "Seni tenzih ederiz, ilmimiz yoktur.", fazilet: "Hataları anlayıp tevazu kazanmak içindir." },
    { vakit: 'aksam', ad: "Hamd-i Ekber", arapca: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", meal: "Allah'ı hamdı ile tesbih ederim.", fazilet: "Yeryüzündeki tüm varlıkların tesbihidir." },
    { vakit: 'aksam', ad: "Kapanış Duası", arapca: "سُبْحَانَ رَبِّكَ رَبِّ الْعِزَّةِ", meal: "İzzet sahibi Rabbin yücedir.", fazilet: "Duaların son mühürleme duasıdır." }
  ],
  zikirler: [
    { id: 1, ad: "Sübhânallâh", arapca: "سُبْحَانَ اللَّهِ", fayda: "Allah'ı noksan sıfatlardan tenzih etmektir.", hedef: 33 },
    { id: 2, ad: "Elhamdülillâh", arapca: "الْحَمْدُ لِلَّهِ", fayda: "Her hal için şükretmektir. Nimeti artırır.", hedef: 33 },
    { id: 3, ad: "Allâhu Ekber", arapca: "اللَّهُ أَكْبَرُ", fayda: "Allah en büyüktür. Nefsi terbiye eder.", hedef: 33 },
    { id: 4, ad: "Lâ ilâhe illallâh", arapca: "لَا إِلٰهَ إِلَّا اللهُ", fayda: "Zikrin en faziletlisidir.", hedef: 99 },
    { id: 5, ad: "Sübhânallâhi ve bi-hamdihi", arapca: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", fayda: "Deniz köpüğü kadar günahı siler.", hedef: 100 },
    { id: 6, ad: "Lâ havle velâ kuvvete...", arapca: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", fayda: "99 derde devadır.", hedef: 100 },
    { id: 7, ad: "Estağfirullâh", arapca: "أَسْتَغْفِرُ اللَّهَ", fayda: "Rızkı genişletir, dertleri def eder.", hedef: 100 },
    { id: 8, ad: "Hasbünallâhu ve ni'mel vekîl", arapca: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", fayda: "Korkulara karşı en büyük emniyettir.", hedef: 33 },
    { id: 9, ad: "Allâhümme salli alâ Muhammed", arapca: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ", fayda: "Peygamberimizin şefaatine vesiledir.", hedef: 100 },
    { id: 10, ad: "Ya Hayyu Ya Kayyum", arapca: "يَا حَيُّ يَا قَيُّومُ", fayda: "Her işin selâmeti ve canlanması içindir.", hedef: 33 },
    { id: 11, ad: "Ya Latif", arapca: "يَا لَطِيفُ", fayda: "İşlerin incelikle hallolması için okunur.", hedef: 129 },
    { id: 12, ad: "Ya Fettah", arapca: "يَا فَتَّاحُ", fayda: "Kapalı kapıların açılması içindir.", hedef: 100 },
    { id: 13, ad: "Ya Rezzak", arapca: "يَا رَزَّاقُ", fayda: "Rızık bereketi için okunur.", hedef: 100 },
    { id: 14, ad: "Ya Şafi", arapca: "يَا شَافِي", fayda: "Hastalıkların şifası için okunur.", hedef: 100 },
    { id: 15, ad: "Ya Vedud", arapca: "يَا وَدُودُ", fayda: "Sevgi ve muhabbeti artırmak içindir.", hedef: 100 },
    { id: 16, ad: "Ya Rahman", arapca: "يَا رَحْمَانُ", fayda: "Allah'ın merhametini celp eder.", hedef: 100 },
    { id: 17, ad: "Ya Rahim", arapca: "يَا رَحِيمُ", fayda: "Dünya ve ahirette merhamet bulmak içindir.", hedef: 100 },
    { id: 18, ad: "Ya Gaffar", arapca: "يَا غَفَّارُ", fayda: "Günahların affı ve örtülmesi içindir.", hedef: 100 },
    { id: 19, ad: "Ya Settar", arapca: "يَا سَتَّارُ", fayda: "Ayıpların örtülmesi için okunur.", hedef: 100 },
    { id: 20, ad: "Ya Hafiz", arapca: "يَا حَفِيظُ", fayda: "Her türlü tehlikeden korunmak içindir.", hedef: 100 },
    { id: 21, ad: "Ya Selam", arapca: "يَا سَلَامُ", fayda: "Huzur ve esenlik bulmak için okunur.", hedef: 100 },
    { id: 22, ad: "Ya Mümin", arapca: "يَا مُؤْمِنُ", fayda: "Gönüllerde iman ışığı yakmak içindir.", hedef: 100 },
    { id: 23, ad: "Ya Muheymin", arapca: "يَا مُهَيْمِنُ", fayda: "Gözetici ve koruyucu Allah'a sığınmaktır.", hedef: 100 },
    { id: 24, ad: "Ya Aziz", arapca: "يَا عَزِيزُ", fayda: "İzzet ve şeref kazanmak için okunur.", hedef: 100 },
    { id: 25, ad: "Ya Cebbar", arapca: "يَا جَبَّارُ", fayda: "Dilediğini zorla yaptıran Allah'ın gücü.", hedef: 100 },
    { id: 26, ad: "Ya Mütekebbir", arapca: "يَا مُتَكَبِّرُ", fayda: "Büyüklük ve azamet sahibi Allah.", hedef: 100 },
    { id: 27, ad: "Ya Halik", arapca: "يَا خَالِقُ", fayda: "Yaratıcı olan Allah'ın adıyla anmak.", hedef: 100 },
    { id: 28, ad: "Ya Bari", arapca: "يَا بَارِئُ", fayda: "Eksiksiz yaratan Allah.", hedef: 100 },
    { id: 29, ad: "Ya Musavvir", arapca: "يَا مُصَوِّرُ", fayda: "Her şeye şekil veren Allah.", hedef: 100 },
    { id: 30, ad: "Ya Kahhar", arapca: "يَا قَهَّارُ", fayda: "Her şeye galip gelen Allah.", hedef: 100 },
    { id: 31, ad: "Ya Vehhab", arapca: "يَا وَهَّابُ", fayda: "Karşılıksız bolca veren Allah.", hedef: 100 },
    { id: 32, ad: "Ya Alim", arapca: "يَا عَلِيمُ", fayda: "Her şeyi en iyi bilen Allah.", hedef: 100 },
    { id: 33, ad: "Ya Kabiz", arapca: "يَا قَابِضُ", fayda: "Dilediğine darlık veren Allah.", hedef: 100 },
    { id: 34, ad: "Ya Basit", arapca: "يَا بَاسِطُ", fayda: "Dilediğine ferahlık veren Allah.", hedef: 100 },
    { id: 35, ad: "Ya Hafid", arapca: "يَا خَافِضُ", fayda: "Kibirliyi alçaltan Allah.", hedef: 100 },
    { id: 36, ad: "Ya Rafi", arapca: "يَا رَافِعُ", fayda: "Müminleri yükselten Allah.", hedef: 100 },
    { id: 37, ad: "Ya Muiz", arapca: "يَا مُعِزُّ", fayda: "İzzet veren Allah.", hedef: 100 },
    { id: 38, ad: "Ya Muzil", arapca: "يَا مُذِلُّ", fayda: "Zillete düşüren Allah.", hedef: 100 },
    { id: 39, ad: "Ya Semi", arapca: "يَا سَمِيعُ", fayda: "Her şeyi işiten Allah.", hedef: 100 },
    { id: 40, ad: "Ya Basir", arapca: "يَا بَصِيرُ", fayda: "Her şeyi gören Allah.", hedef: 100 },
    { id: 41, ad: "Ya Hakem", arapca: "يَا حَكَمُ", fayda: "Hükmeden Allah.", hedef: 100 },
    { id: 42, ad: "Ya Adl", arapca: "يَا عَدْلُ", fayda: "Mutlak adil olan Allah.", hedef: 100 },
    { id: 43, ad: "Ya Habir", arapca: "يَا خَبِيرُ", fayda: "Her şeyden haberdar olan.", hedef: 100 },
    { id: 44, ad: "Ya Halim", arapca: "يَا حَلِيمُ", fayda: "Yumuşak davranan Allah.", hedef: 100 },
    { id: 45, ad: "Ya Azim", arapca: "يَا عَظِيمُ", fayda: "Pek yüce olan Allah.", hedef: 100 },
    { id: 46, ad: "Ya Şekur", arapca: "يَا شَكُورُ", fayda: "Az amele çok sevap veren.", hedef: 100 },
    { id: 47, ad: "Ya Aliy", arapca: "يَا عَلِيُّ", fayda: "Yüceler yücesi Allah.", hedef: 100 },
    { id: 48, ad: "Ya Kebir", arapca: "يَا كَبِيرُ", fayda: "En büyük olan Allah.", hedef: 100 },
    { id: 49, ad: "Ya Mukit", arapca: "يَا مُقِيتُ", fayda: "Rızıkları yaratan Allah.", hedef: 100 },
    { id: 50, ad: "Ya Hasib", arapca: "يَا حَسِيبُ", fayda: "Hesapları en iyi gören.", hedef: 100 },
    { id: 51, ad: "Ya Kerim", arapca: "يَا كَرِيمُ", fayda: "Cömertliği sınırsız olan.", hedef: 100 },
    { id: 52, ad: "Ya Rakib", arapca: "يَا رَقِيبُ", fayda: "Her an gözeten Allah.", hedef: 100 },
    { id: 53, ad: "Ya Mucib", arapca: "يَا مُجِيبُ", fayda: "Duaları kabul eden.", hedef: 100 },
    { id: 54, ad: "Ya Vasi", arapca: "يَا وَاسِعُ", fayda: "İlmi sınırsız olan.", hedef: 100 },
    { id: 55, ad: "Ya Hakim", arapca: "يَا حَكِيمُ", fayda: "Hikmet sahibi Allah.", hedef: 100 },
    { id: 56, ad: "Ya Mecid", arapca: "يَا مَجِيدُ", fayda: "Şanı pek yüce olan.", hedef: 100 },
    { id: 57, ad: "Ya Bais", arapca: "يَا بَاعِثُ", fayda: "Ölüleri dirilten Allah.", hedef: 100 },
    { id: 58, ad: "Ya Şehid", arapca: "يَا شَهِيدُ", fayda: "Her şeye şahit olan.", hedef: 100 },
    { id: 59, ad: "Ya Hakk", arapca: "يَا حَقُّ", fayda: "Varlığı değişmeyen hakikat.", hedef: 100 },
    { id: 60, ad: "Tevekkeltü Alallâh", arapca: "تَوَكَّلْتُ عَلَى اللَّهِ", fayda: "İşi Allah'a bırakmak, huzur sağlar.", hedef: 33 }
  ]
};
